name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.*]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./dev-requirements.txt
        pip install -r ./src/requirements.txt

    - name: Run linting
      env:
        SKIP: no-commit-to-branch
      run: |
        pre-commit run --all-files
        mypy .

    - name: Run tests
      run: pytest
